/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipeProtectedAddRecipeRouteImport } from './routes/recipe/_protected/add-recipe'
import { Route as RecipeProtectedProtectedRouteImport } from './routes/recipe/_protected/_protected'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeProtectedAddRecipeRoute =
  RecipeProtectedAddRecipeRouteImport.update({
    id: '/recipe/_protected/add-recipe',
    path: '/recipe/add-recipe',
    getParentRoute: () => rootRouteImport,
  } as any)
const RecipeProtectedProtectedRoute =
  RecipeProtectedProtectedRouteImport.update({
    id: '/recipe/_protected/_protected',
    path: '/recipe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/recipe': typeof RecipeProtectedProtectedRoute
  '/recipe/add-recipe': typeof RecipeProtectedAddRecipeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/recipe': typeof RecipeProtectedProtectedRoute
  '/recipe/add-recipe': typeof RecipeProtectedAddRecipeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/recipe/_protected/_protected': typeof RecipeProtectedProtectedRoute
  '/recipe/_protected/add-recipe': typeof RecipeProtectedAddRecipeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/recipe' | '/recipe/add-recipe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/recipe' | '/recipe/add-recipe'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/recipe/_protected/_protected'
    | '/recipe/_protected/add-recipe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  RecipeProtectedProtectedRoute: typeof RecipeProtectedProtectedRoute
  RecipeProtectedAddRecipeRoute: typeof RecipeProtectedAddRecipeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/_protected/add-recipe': {
      id: '/recipe/_protected/add-recipe'
      path: '/recipe/add-recipe'
      fullPath: '/recipe/add-recipe'
      preLoaderRoute: typeof RecipeProtectedAddRecipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/_protected/_protected': {
      id: '/recipe/_protected/_protected'
      path: '/recipe'
      fullPath: '/recipe'
      preLoaderRoute: typeof RecipeProtectedProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  RecipeProtectedProtectedRoute: RecipeProtectedProtectedRoute,
  RecipeProtectedAddRecipeRoute: RecipeProtectedAddRecipeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
